apiVersion: v1
kind: Pod
metadata:
    name: frontend
    labels:
        app: overwatch-app
spec:
    containers:
        - name: frontend
          image: frontend:latest
          ports:
              - name: web
                containerPort: 80
                protocol: TCP

