name: CI

on: [push]

jobs:
  eslint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front_end
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint front end
        run: eslint . --ext .js,.jsx,.ts,.tsx